### ISSUE TITLE
A failed QGL in combination with MAG Probe would still run into a issue during prime line

### ISSUE THREAD

**Issue by Piranha1511** [zellneralex/klipper_config#21]
Even with the latest commit, a failed QGL (e.g. due to a not probably docked probe) would still run into a issue during prime line and before print.

Since the CHECK_QGL will be executed after the prime line! 

Result: MAG Probe (e.g. Klicky) can smash into the bed.

**Comment by zellneralex** [comment]
First off all a mag probe should not be able to smash in the bed. The G0/G1 micro should prevent that. https://github.com/zellneralex/klipper_config/blob/master/magprobe.cfg#L157.

I do not have a better solution! The add of the error code section in [virtual sdcard] may prevent that at all but I had no time yet to test it.

**Comment by Piranha1511** [comment]
On my printer it is still a issue if you run a second print. A new QGL will not be performed and QGL is still seen as "true", but a bed mesh was performed before. If the probe is not probably docked after bed mesh, it will smash into the bed.

**Comment by zellneralex** [comment]
I am not sure what you mean by that, but as I stated it many times. See that config as something you can get ideas.

As you see in my config I do no mesh, if you have a problem there you should work on a solution.
But https://github.com/zellneralex/klipper_config/blob/master/probe_qgl.cfg#L111 should detect your docking failure
And if your probe would still show docked this would prevent the smashing in the bed https://github.com/zellneralex/klipper_config/blob/master/magprobe.cfg#L168

or does your probe stays “half” on so that it is detected as docked. Then I really recommend to make your docking more reliable as that can not be detected at all.

**Comment by zellneralex** [comment]
And yes that’s the main problem with all the mag probes. If you can not get it to reliable undock you risk to smash it in the bed.
That’s the reason why my macro use an 90 degree angle to avoid that.

That’s also one reason why I will switch to Voron Tap soon.
